=== ik902a/XmlXsdWebParsing/src/main/resources/data_xml/papers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.com/papers"
	xmlns:tns="http://www.example.com/papers"
	elementFormDefault="qualified">

	<element name="papers">
		<complexType>
			<sequence>
				<element ref="tns:paper" minOccurs="16" maxOccurs="50" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Paper">
		<sequence>
			<element name="title" type="string" />
			<element name="date" type="date" />
			<element name="is-monthly" type="boolean" />
			<element name="is-color" type="boolean" />
			<element name="number-pages" type="tns:NumberPages" />
		</sequence>
		<attribute name="id" type="tns:Id" use="required" />
		<attribute name="theme" use="optional" default="news">
			<simpleType>
				<restriction base="string">
					<enumeration value="life"></enumeration>
					<enumeration value="people"></enumeration>
					<enumeration value="computerGames"></enumeration>
					<enumeration value="nature"></enumeration>
					<enumeration value="sport"></enumeration>
					<enumeration value="cars"></enumeration>
					<enumeration value="science"></enumeration>
					<enumeration value="news"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<simpleType name="Id">
		<restriction base="ID">
			<pattern value="p\d{3}" />
		</restriction>
	</simpleType>

	<complexType name="Newspaper">
		<complexContent>
			<extension base="tns:Paper">
				<sequence>
					<element name="is-glossy" type="boolean" fixed="false"/>
					<element name="subscript-index" type="tns:SubscriptIndex" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="Magazine">
		<complexContent>
			<extension base="tns:Paper">
				<sequence>
					<element name="is-glossy" type="boolean" fixed="true"/>
					<element name="subscript-index" type="tns:SubscriptIndex" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="Booklet">
		<complexContent>
			<extension base="tns:Paper">
				<sequence>
					<element name="is-glossy" type="boolean" fixed="true"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<simpleType name="NumberPages">
		<restriction base="positiveInteger">
			<minInclusive value="2" />
			<maxInclusive value="1000" />
		</restriction>
	</simpleType>

	<simpleType name="SubscriptIndex">
		<restriction base="string">
			<pattern value="\d{5,7}" />
		</restriction>
	</simpleType>

	<element name="paper" type="tns:Paper" abstract="true" />
	<element name="newspaper" type="tns:Newspaper" substitutionGroup="tns:paper" />
	<element name="magazine" type="tns:Magazine" substitutionGroup="tns:paper" />
	<element name="booklet" type="tns:Booklet" substitutionGroup="tns:paper" />
</schema>

=== ik902a/XmlXsdWebParsing/data_xml/papers_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<papers 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xmlns="http://www.example.com/papers"
			xsi:schemaLocation="http://www.example.com/papers papers.xsd">
	
	<newspaper id="p001" theme="news">
		<title>Советская Белоруссия</title>
		<date>2021-01-30</date>
		<is-monthly>true</is-monthly>
		<is-color>true</is-color>
		<number-pages>30</number-pages>
		<is-glossy>false</is-glossy>
		<subscript-index>00001</subscript-index>
	</newspaper>
	
	<magazine id="p555">
		<title>Time</title>
		<date>2021-01-29</date>
		<is-monthly>false</is-monthly>
		<is-color>true</is-color>
		<number-pages>100</number-pages>
		<is-glossy>true</is-glossy>
		<subscript-index>555055</subscript-index>
	</magazine>
	
	<booklet id="p666" theme="nature">
		<title>Stop pollution</title>
		<date>2021-01-15</date>
		<is-monthly>false</is-monthly>
		<is-color>true</is-color>
		<number-pages>2</number-pages>
		<is-glossy>true</is-glossy>
	</booklet>
	
	<newspaper id="p069" theme="news">
		<title>Die Zeit</title>
		<date>2021-01-30</date>
		<is-monthly>true</is-monthly>
		<is-color>true</is-color>
		<number-pages>26</number-pages>
		<is-glossy>false</is-glossy>
		<subscript-index>69001</subscript-index>
	</newspaper>
	
	<magazine id="p557" theme="people">
		<title>Forbes</title>
		<date>2021-01-25</date>
		<is-monthly>false</is-monthly>
		<is-color>true</is-color>
		<number-pages>150</number-pages>
		<is-glossy>true</is-glossy>
		<subscript-index>777077</subscript-index>
	</magazine>
</papers>

=== ik902a/XmlXsdWebParsing/src/main/resources/data_xml/papers.xml
<?xml version="1.0" encoding="UTF-8"?>
<papers 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xmlns="http://www.example.com/papers"
			xsi:schemaLocation="http://www.example.com/papers papers.xsd">
	
	<newspaper id="p001" theme="news">
		<title>Советская Белоруссия</title>
		<date>2021-01-30</date>
		<is-monthly>true</is-monthly>
		<is-color>true</is-color>
		<number-pages>30</number-pages>
		<is-glossy>false</is-glossy>
		<subscript-index>00001</subscript-index>
	</newspaper>
	
	<magazine id="p555">
		<title>Time</title>
		<date>2021-01-29</date>
		<is-monthly>false</is-monthly>
		<is-color>true</is-color>
		<number-pages>100</number-pages>
		<is-glossy>true</is-glossy>
		<subscript-index>555055</subscript-index>
	</magazine>
	
	<booklet id="p666" theme="nature">
		<title>Stop pollution</title>
		<date>2021-01-15</date>
		<is-monthly>false</is-monthly>
		<is-color>true</is-color>
		<number-pages>2</number-pages>
		<is-glossy>true</is-glossy>
	</booklet>
	
	<newspaper id="p069" theme="news">
		<title>Die Zeit</title>
		<date>2021-01-30</date>
		<is-monthly>true</is-monthly>
		<is-color>true</is-color>
		<number-pages>26</number-pages>
		<is-glossy>false</is-glossy>
		<subscript-index>69001</subscript-index>
	</newspaper>
	
	<magazine id="p557" theme="people">
		<title>Forbes</title>
		<date>2021-01-25</date>
		<is-monthly>false</is-monthly>
		<is-color>true</is-color>
		<number-pages>150</number-pages>
		<is-glossy>true</is-glossy>
		<subscript-index>777077</subscript-index>
	</magazine>
	
	<magazine id="p042" theme="computerGames">
		<title>Игромания</title>
		<date>2021-01-15</date>
		<is-monthly>false</is-monthly>
		<is-color>true</is-color>
		<number-pages>350</number-pages>
		<is-glossy>true</is-glossy>
		<subscript-index>7770042</subscript-index>
	</magazine>
	
	<magazine id="p111" theme="science">
		<title>Техника молодежи</title>
		<date>2021-01-23</date>
		<is-monthly>true</is-monthly>
		<is-color>true</is-color>
		<number-pages>170</number-pages>
		<is-glossy>true</is-glossy>
		<subscript-index>71112</subscript-index>
	</magazine>
	
	<newspaper id="p123" theme="sport">
		<title>Спорт Экспресс</title>
		<date>2021-01-30</date>
		<is-monthly>false</is-monthly>
		<is-color>false</is-color>
		<number-pages>16</number-pages>
		<is-glossy>false</is-glossy>
		<subscript-index>123456</subscript-index>
	</newspaper>
	
	<newspaper id="p224" theme="news">
		<title>Правда</title>
		<date>2021-01-10</date>
		<is-monthly>true</is-monthly>
		<is-color>false</is-color>
		<number-pages>20</number-pages>
		<is-glossy>false</is-glossy>
		<subscript-index>22405</subscript-index>
	</newspaper>
	
	<booklet id="p669" theme="nature">
		<title>Facts about AIDS</title>
		<date>2021-01-30</date>
		<is-monthly>false</is-monthly>
		<is-color>true</is-color>
		<number-pages>10</number-pages>
		<is-glossy>true</is-glossy>
	</booklet>
	
	<magazine id="p424" theme="cars">
		<title>Top Gear</title>
		<date>2021-01-13</date>
		<is-monthly>true</is-monthly>
		<is-color>true</is-color>
		<number-pages>250</number-pages>
		<is-glossy>true</is-glossy>
		<subscript-index>8234573</subscript-index>
	</magazine>
	
	<magazine id="p888" theme="nature">
		<title>nature</title>
		<date>2021-01-17</date>
		<is-monthly>true</is-monthly>
		<is-color>true</is-color>
		<number-pages>120</number-pages>
		<is-glossy>true</is-glossy>
		<subscript-index>78882</subscript-index>
	</magazine>
	
	<magazine id="p991" theme="people">
		<title>GQ</title>
		<date>2021-01-21</date>
		<is-monthly>true</is-monthly>
		<is-color>true</is-color>
		<number-pages>120</number-pages>
		<is-glossy>true</is-glossy>
		<subscript-index>797979</subscript-index>
	</magazine>
	
	<newspaper id="p646">
		<title>The New York times</title>
		<date>2021-01-30</date>
		<is-monthly>true</is-monthly>
		<is-color>false</is-color>
		<number-pages>30</number-pages>
		<is-glossy>false</is-glossy>
		<subscript-index>1646555</subscript-index>
	</newspaper>
	
	<magazine id="p332" theme="people">
		<title>Maxim</title>
		<date>2021-01-30</date>
		<is-monthly>true</is-monthly>
		<is-color>true</is-color>
		<number-pages>330</number-pages>
		<is-glossy>true</is-glossy>
		<subscript-index>323232</subscript-index>
	</magazine>
	
	<magazine id="p011" theme="computerGames">
		<title>Famitsu</title>
		<date>2021-01-29</date>
		<is-monthly>true</is-monthly>
		<is-color>true</is-color>
		<number-pages>320</number-pages>
		<is-glossy>true</is-glossy>
		<subscript-index>011001</subscript-index>
	</magazine>
	
	<newspaper id="p283" theme="news">
		<title>The guardian</title>
		<date>2021-01-27</date>
		<is-monthly>false</is-monthly>
		<is-color>true</is-color>
		<number-pages>30</number-pages>
		<is-glossy>false</is-glossy>
		<subscript-index>352550</subscript-index>
	</newspaper>
	
</papers>
